# Generated by Django 4.1 on 2025-10-24 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0002_profile_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='bot_reply',
            new_name='bot_response',
        ),
    ]
